### ISSUE TITLE
Communication between ViewModel and Model

### ISSUE THREAD

**Issue by rayworks** [inloop/AndroidViewModel#12]
Hi there, 
Glad to see this library handles Android life cycle quite well and AndroidViewModel does prove itself a great VM framework.

From the architecture diagram, I was wondering is it possible the ViewModel would deal with _business Model_ instead of actual data component(DB, WebService...). If possible, how can I extend the existing framework ? What's your opinion ?

**Comment by DanielNovak** [comment]
@rayworks Sorry for the late reply. I am not sure if I understand your question correctly. I usually have some "Service" (not Android Service) classes that contain the business logic, that could be a simple plain singleton (in an ideal case it would be just stateless) and I am not manipulating data or doing too much code in the ViewModel - instead I am calling those service classes to do the work. 
The ViewModel class is bound to the lifecycle of the Activity/Fragment, so it doesn't make much sense to me to have another type of "BussinessViewModel" class...

**Comment by rayworks** [comment]
@DanielNovak Thank you for the reply.

Yeah, that's what I mean. Is it necessary to have a "business layer" which contains the "Model" and "Service" as you mentioned besides the ViewModel ?

> I am not manipulating data or doing too much code in the ViewModel - instead I am calling those 

> service classes to do the work. 

Then how do you organise the "Service" to execute the logic operations and do you involve the related business "Model" or do it via a specific "Service" (on its own)?

**Comment by DanielNovak** [comment]
Maybe I will try to explain how I usually do it on examples. For example you need to load a list of users from an API, so you have some sort of ApiService which has a method like ApiService.getUsers(ResultCallback result). In my ViewModel I just execute this method and in the callback methods I am sending the data to the View. I am trying to keep the hierarchy flat.

But I am not sending a direct reference of the ViewModel to the ApiService or any other layer. The ViewModel is directly calling other Service classes and handling the results. The ViewModel instance is never shared with other views or layers.

**Comment by rayworks** [comment]
OK, good to know the use case as you mentioned. So, is there any logic which remote ApiService can't  do on its own?  Let's make a assumption, it depends on the local status. eg. the user will pass a test if he/she has scored 60 points or more for all the loaded questions (the interaction with each test item required certainly).

Should this kind of logic also be put into ViewModel or other related business service ?

Thank you for helping clarify things in my mind.
