### ISSUE TITLE
More consistent naming convention

### ISSUE THREAD

**Issue by petrnohejl** [inloop/AndroidViewModel#13]
I suggest to rename some life-cycle methods in [AbstractViewModel.java](https://github.com/inloop/AndroidViewModel/blob/master/library/src/main/java/eu/inloop/viewmodel/AbstractViewModel.java) to make it more consistent. I am talking especially about **bindView**, **saveState** and **onModelRemoved**. All these methods are dependent on Activity/Fragment life-cycle and it would be very nice to follow the same naming convention as Activity/Fragment's methods do.

Methods should be prefixed with "on" and the action should be described in the present tense, not the passive (e.g. _onCreate_).

So I suggest to rename the methods like this:

**bindView -> onBindView**
Similar convention to _Fragment.onCreateView_ or _onDestroyView_. Eventually it might be also "_onViewBound_" like _Fragment.onViewCreated_ or _onActivityCreated_.

**saveState -> onSaveInstanceState**
To make it consistent with Activity/Fragment naming convention.

**onModelRemoved -> onDestroy**
It is called when the fragment or view is already gone and destroyed so this name makes sense. Also, as opposite to "_onCreate_", it makes more sense than "_onModelRemoved_". Moreover, the word "Model" in the name might be a bit confusing, because it is about ViewModel and not Model, right?

What do you say? I think these changes would make the code better readable. Thanks.

**Comment by DanielNovak** [comment]
That's definitely a very good suggestion, and you are absolutely right - the naming isn't consistent. I am thinking how to do it without forcing developers to change their code, but there is probably no other way (I could make the old methods deprecated, but that would be just confusing).

**Comment by petrnohejl** [comment]
Hi Dan. I agree, making the old methods deprecated might be confusing. I know it is a breaking change, but on the other hand, refactoring the code in existing projects should be very easy - developers just have to rename 3 methods. Maybe you can promote a version of the library to 1.0.0 to indicate the change in the API.

**Comment by FrantisekGazo** [comment]
Good idea, but changing **onModelRemoved()** to **onDestroy()** could be confusing, because this method is called when Activity or Fragment is finishing, not every time **onDestroy()** is called. So this one should stay as is or change to something like **onRemove()**, in my opinion.

**Comment by petrnohejl** [comment]
That's a good point, but we are talking about **ViewModel.onDestroy()** which should be called when the ViewModel itself is being destroyed. The naming convention is consistent, the moment when it is called is a bit different (in relation with Activity/Fragment), but the method is called when it is **being destroyed** (same behavior as Activity/Fragment), so in this matter, it makes sense. It is a similar situation as Activity vs. Fragment - for example Fragment.onCreate() is not called everytime when Activity.onCreate() is called (e.g. creating fragment instances in a view pager when you are swiping). I think it is not about when exactly it is called in the Activity/Fragment lifecycle, but rather in which situation it is called in ViewModel lifecycle.

I understand it might be confusing in relation with Activity/Fragment lifecycle, but still I think that onDestroy() name makes sense. It is just my personal opinion, onRemove() could be also good name, definitely better than onModelRemoved().

**Comment by DanielNovak** [comment]
Fixed (will be part of 1.0.0 release)
