### ISSUE TITLE
ViewModel object creation - use Dagger 2

### ISSUE THREAD

**Issue by dozd** [inloop/AndroidViewModel#17]
Hi,

When you want to use this library with some kind of dependency injection aka Dagger 2, you have no control over creating instance of `ViewModel`.

So I've made a little change in API. Instead of having abstract `getViewModelClass()`, i'm having `createViewModel()` defined on fragments / activities. Then i can use whatever I want to create my `ViewModel` object. This is good for IOC as well as having non default construtors etc.

This could be also done with some hard tunning `ViewModelProvider` (private constructor there), but this change to API looks way better for me. You can check it out at https://github.com/dozd/AndroidViewModel/commit/827b4945793e07814445f2a6ebb46426cda45b71

**Comment by FrantisekGazo** [comment]
@dozd You can also try **Blade** `mvp` module - it allows you to inject `Presenter`s via Dagger2.

**Comment by micutad** [comment]
@dozd what about change of dependencies in component? If you inject them to ViewModel during creation through constructor, they can be no longer valid when activity subcomponent is recreated.
You load ViewModel with old dependencies from previous Subcomponent.
What about creating ViewModel without dependencies and reinject it when he is loaded from ViewModelProvider?

**Comment by dozd** [comment]
@micutad I can't imagine that dependencies have "shorter life" than ViewModel. One ViewModel cannot be shared through various Subcomponents as it's bound to the specific fragment that is in specific subcomponent.

Creating class without dependencies and injecting them during life-time of the class is anti-pattern in terms of mutability of the class. Dependency injection is about *creating* class with their dependencies easily not about managing them during the time of the class.

**Comment by micutad** [comment]
@dozd 
If you have activity subcomponent than this subcomponent is recreated on config change because old activity is destroyed with current subcomponent, and new activity is created with new subcomponent.

If ViewModel is injected with this subcomponent and saved on config change then all dependencies are invalid after loading retained ViewModel because new activity have new subcomponent with new dependencies.

Not sure if Im explaining this clearly but in my case I have dependencies in ViewModel that are from Activity subcomponent and not from Application component.

**Comment by dozd** [comment]
How's your ViewModel living longer than activity? That sounds weird.

**Comment by micutad** [comment]
isnt it the one of main purpouses of this library? saving ViewModel during
recreation?

**Comment by dozd** [comment]
But for one fragment. And fragment does not live longer than activity as well.

**Comment by micutad** [comment]
it saves ViewModels for all fragments inside activity. than activity is
recreated and also fragments are recreated and saved ViewModels are
delivered to fragments. new Activity subcomponent is created and its
dependencies are different that dependencies in saved ViewModel.
