### ISSUE TITLE
View and ViewModel as a parent class

### ISSUE THREAD

**Issue by tymm** [inloop/AndroidViewModel#18]
Is it possible to have a View and a ViewModel which act as a parent class to a subclass View and ViewModel where the parent class and the subclass define different contracts (IViews)?

I tried to do that but without success.

**Comment by petrnohejl** [comment]
It is possible. See my example app https://github.com/petrnohejl/Android-Stocks which uses this library and check the code:

Parent classes:
- BaseView.java
- BaseViewModel.java
- BaseFragment.java

Sub-classes:
- HelloWorldView.java
- HelloWorldViewModel.java
- HelloWorldFragment.java

**Comment by tymm** [comment]
Thanks, that helped me a lot :)
