### ISSUE TITLE
Context for ViewModel

### ISSUE THREAD

**Issue by traninho** [inloop/AndroidViewModel#5]
Hi, thank you for the lib. I am wondering, how I can access to associated Activity/Fragment from ViewModel class.

Imagine this simple use case: 

1) Activity/Fragment has some list of items
2) Clicking on an item should open a new detail activity 
3) Clicking on an item is handled by Activity/Fragment and is delegated to the associated ViewModel class.
4) The associated ViewModel class should open a new detail activity of the selected item. But this action requires a Context class. 

How would you solve this? Or should "start a detail activity" action be delegated back to the activity/fragment via getView().startDetailScreen()?

**Comment by F3roG** [comment]
I think the best way to navigate to the next activity is from View like you said at the end (use callback).

Because ViewModel shouldn't have reference to activity's context - it changes on rotation. 
You could cast getView() to Context, but I don't think it's a good idea.

But that's just my opinion. :)

**Comment by DanielNovak** [comment]
That's how we are using it -  getView().startDetailScreen(). This way you don't have any Activity or Fragment references in the code - which also means that the ViewModel layer is separated from Android specific classes and testing is also easier. 
Ideally you should not be touching Context inside ViewModel, except for ApplicationContext (which you can share from a singleton to not polute the interfaces with "getContext()" methods)
