### ISSUE TITLE
Other open source projects using AndroidViewModel....

### ISSUE THREAD

**Issue by sirvon** [inloop/AndroidViewModel#6]
Thanks for this timely lib!

Can you point me in the direction of other projects that use this lib.

I would like to see more variety and styles of how other devs are implementing the lib.

thanks!

**Comment by petrnohejl** [comment]
I use this library in my experimental project Stocks. I implemented MVVM architecture along with the Android Data Binding. It works pretty well and business logic is separate from UI. I am going to use this architecture in my future apps. You can check my source code here: https://github.com/petrnohejl/Android-Stocks and see how to use AndroidViewModel with other technologies/libraries like RecyclerView, Retrofit, Glide, RxJava etc.
