### ISSUE TITLE
How to get or inject context in viewmodel...

### ISSUE THREAD

**Issue by sirvon** [inloop/AndroidViewModel#7]
I would I inject or get the context in the viewmodel.

There will be lots of statements and commands I will want to invoke in the viewmodel that
will need a context.

For instance this statement:
```java

((App) getApplication()).inject(this);

```

How would I get that going in the viewmodel?

thanks!

**Comment by DanielNovak** [comment]
You can keep a static reference to the application context (not activity context!) and use it.
For example, in your application class you will have something like this:

```java
    class App extends Application { 
   
    public static Context sContext; 
  
        public void onCreate() {
             super.onCreate();
             sInstance = this;
          }
    }
```

And then in your ViewModel just use ``` App.sContext``` to get the application context. This doesn't look that great but works and I have seen it used in a lot of large projects. And you don't need to pollute the ViewModel interfaces / methods with the context.

**Comment by sirvon** [comment]
Application class:
```java
public static Context mContext;
    private ObjectGraph objectGraph;
    @Inject PubnubServices pubnubServices;
    @Inject Rxbus rxbus;
    DeviceInfo dvinfo = new DeviceInfo(this);
    @InjectService SupportService supportService;
    private RefWatcher refWatcher;
    String emailAddress;

    @Override
    public void onCreate() {
        AsyncService.inject(this);
        instance = this;
        super.onCreate();
        AndroidThreeTen.init(this);
        objectGraph = ObjectGraph.create(getModules().toArray());
        refWatcher = LeakCanary.install(this);
        mContext = this;
```

A ViewModel:
```java
public class USDJPYNewsFeedViewModel extends AbstractViewModel<IUSDJPYNewsFeedView>{

    String TAG = "loqootv";
    @Inject Context context;
    LoQooApp baseApp;


    @Override
    public void onCreate(@Nullable Bundle arguments, @Nullable Bundle savedInstanceState) {
        super.onCreate(arguments, savedInstanceState);

        ((LoQooApp) baseApp.mContext.getApplication()).inject(baseApp.mContext);
````

in the viewModel the getApplication() is in red

I replace that statement with this:
```java
((LoQooApp) baseApp.mContext).inject(baseApp.mContext);
```

and no red but I haven't compiled it yet...
what do ya think??
