### ISSUE TITLE
transfer this rx subscription code from View to ViewModel....

### ISSUE THREAD

**Issue by sirvon** [inloop/AndroidViewModel#8]
I have this code operational and running beautifully if I might add, but it's running inside the view.
Which in this case is a fragment....

From EURUSDSequenceView:

``` java
rxBus.toObserverable()//
                .compose(bindToLifecycle())
                .ofType(EURUSDPercentD.class)
                .map(new Func1<EURUSDPercentD, JSONObject>() {
                    @Override
                    public JSONObject call(final EURUSDPercentD event) {
                        return event.getEvent();
                    }
                })
                .subscribe(new Action1<JSONObject>() {
                    @Override
                    public void call(final JSONObject message) {
                        if (eurusdSeqViewIsVisible.equals("true")) {
                            incomingData = true;
                            Log.d(TAG, "From: EURUSDSeqView, Msg: " + message.toString());

......
```

How can I get that code operational inside the viewModel because once those streams come in there is manipulation of the view going on...visibility, changing colors, saving data to prefs/dbs etc, etc
OR
should I just leave the subscription inside the view and then call to the viewModel accordingly?

thanks!

**Comment by ninadmg** [comment]
Changing Visibility and colors should be done from the view. Have a method like setvisiblilyOfButton() in view interface and call getview().setvisiblilyOfButton() from the viewModel.
