### ISSUE TITLE
Please help : "cannot resolve symbol 'T'

### ISSUE THREAD

**Issue by gam101** [inloop/AndroidViewModel#9]
Greetings! I am new to Android & trying to adopt your AndroidViewModel into my project.  I am currently stuck on building the project because ;

@Nullable
private T mView;

throws the exception "cannot resolve symbol 'T'.  Could you please guide me as to what I am missing? Any help will go a long way.....

Thank you.

-Remy

**Comment by ninadmg** [comment]
In which class are you getting the error?
your class should have say what T means like
public class ClassName<T>

**Comment by gam101** [comment]
I appreciate the prompt reply.

Please note that all classes have the error, wherever "T" is referenced. So, its in 

1)"AbstractViewModel", 
private T mView;

2)"ViewModelBaseActivity"
private final ViewModelHelper<T, R> mViewModeHelper = new ViewModelHelper<>();
I was able to resolve the same error for "R" above by adding "import com.mydomain.mysampleapp.R" to that class.

3) "ViewModelBaseFragment"
private final ViewModelHelper<T, R> mViewModeHelper = new ViewModelHelper<>();

4)"ViewModelHelper"
 public void setView(@NonNull T view) {

I want to thank you for sharing this code of yours. What I particularly appreciate about it is that you went out of the way to explain what it is & how to use it. Most of the similar posts here on GitHub have great code, however, they all lack what you have done. That explanation makes it easy to understand, especially for those who are new to Java & Android. So, again, thank you.

And I hope its ok if I ask more questions as I try to adapt it to my project.

-Remy

**Comment by gam101** [comment]
Hello again! Please let me know if you got the chance to look at my reply above. Thank you.

**Comment by DanielNovak** [comment]
"I was able to resolve the same error for "R" above by adding "import com.mydomain.mysampleapp.R" to that class." 
That is not a correct fix, the R is a java generics symbol. It's not the generated R class.
Are you using Android Studio? Maybe your java compile option is lower than 1.7. Can you add this to your build.gradle file?

android {   
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_1_7
		targetCompatibility JavaVersion.VERSION_1_7
	}
}

Can you maybe share the source code somehow? I could take a look.

**Comment by gam101** [comment]
Thank you for your reply.

Yes, I am using Android Studio 1.2.2.

I have now removed the "R" import.  However, please explain what do you mean by "generated R class"?  Is "T" also a "generated class" ?

My code is the same as your sample code. I have not changed anything because I just want to first build it in my project, before I make changes.  For example, the class AbstractViewModel.java is the same as below;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;


/**
 * Created : 9/3/2015
 * TODO: Add a class header comment!
 */
public class AbstractViewModel {
    private String mUniqueIdentifier;

    @Nullable
    private T mView;

    void setUniqueIdentifier(String uniqueIdentifier) {
        mUniqueIdentifier = uniqueIdentifier;
    }

    /**
     *
     * @return An app unique identifier for the current viewmodel instance (will be kept during orientation
     * change). This identifier will be reset in case the corresponding activity is killed.
     */
    public String getUniqueIdentifier() {
        return mUniqueIdentifier;
    }

    /**
     * Called when the ViewModel instance is created.
     * @param arguments initial ViewModel arguments passed from {@link Fragment#getArguments()}  or
     *                  {@link Activity#getIntent()}.{@link Intent#getExtras()}
     * @param savedInstanceState bundle with saved state, will be not null
     *               only in case the system is killed due to low memory
     *               and restored (and {@link #saveState(Bundle)} returned a non-null bundle.
     */
    @SuppressWarnings("EmptyMethod")
    public void onCreate(@Nullable Bundle arguments, @Nullable Bundle savedInstanceState) {

    }

    public void bindView(@NonNull T view) {
        mView = view;
    }

    public T getView() {
        return mView;
    }

    public void clearView() {
        mView = null;
    }

    @SuppressWarnings("EmptyMethod")
    public void saveState(Bundle bundle) {

    }

    @SuppressWarnings("EmptyMethod")
    public void onStop() {

    }

    @SuppressWarnings("EmptyMethod")
    public void onStart() {

    }

    /**
     * Called when there parent fragment or view is already gone and destroyed.
     * This is a good place to empty any planned tasks that are useless without a UI.
     */
    @SuppressWarnings("EmptyMethod")
    public void onModelRemoved() {

    }
}

**Comment by gam101** [comment]
I forgot to mention that I did modify my build.gradle, like you suggested.  However, it did not help with "T" unresolved symbol exception.

apply plugin: 'com.android.application'
apply plugin: 'maven'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.cardinaltracking.ttma"
        minSdkVersion 21
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    dependencies {
        compile 'com.android.support:support-annotations:22.2.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            minifyEnabled false
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile files('libs/eventbus-3.0.0-beta1.jar')
    compile 'com.squareup.dagger:dagger:1.2.1'
}

**Comment by ninadmg** [comment]
Your class should be something like
"public class AbstractViewModel<T>" to use private T mView
please learn java generics to understand more from http://www.tutorialspoint.com/java/java_generics.htm

**Comment by DanielNovak** [comment]
The class would have to be defined as

**Comment by DanielNovak** [comment]
The class would be to be defined as 

         public abstract class AbstractViewModel<T extends IView>

But why are you putting a copy of the AbstractViewModel class into your project? This is already defined in the library. Take a look at the sample project - it does not contain the AbstractViewModel, it's just referencing it from the library.

**Comment by gam101** [comment]
@ninadmg @DanielNovak  Thank you for all the help & your patience.  I was able to resolve "T" after specifying the generic type declarations.  

@DanielNovak, I just checked out the Sample project & yes, just the "base" is being referenced from the library.  In my project, I have the entire Library added, so that is why I have the other classes like the "AbstractViewModel" class. 

If you know a better way that I can add the library module into my project, please do guide me.

Thank you, again.
